//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio_Tourist.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class T_AD
    {
        public int ID_AD { get; set; }

        [DisplayName("Image")]
        [Required(ErrorMessage = "L'image est obligatoire")]
        public string PICTURES_AD { get; set; }

        [DisplayName("Titre")]
        [Required(ErrorMessage = "Le titre est obligatoire")]
        public string TITLE_AD { get; set; }

        [DisplayName("Nom")]
        [Required(ErrorMessage = "Le nom est obligatoire")]
        public string NAME_AD { get; set; }

        [DisplayName("€")]
        [Required(ErrorMessage = "Le prix est obligatoire")]

        public double PRICE_AD { get; set; }

        [DisplayName("Adresse")]
        [Required(ErrorMessage = "L'Adresse est obligatoire")]
        public string ADRESS_AD { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "La description est obligatoire")]
        public string DESCRIPTION_AD { get; set; }

        [DisplayName("Durée")]
        [Required(ErrorMessage = "La date est obligatoire")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime DATE_AD { get; set; }
        public int ID_USER { get; set; }

        [DisplayName("Stock")]
        [Required(ErrorMessage = "Le stock est obligatoire")]
        public int STOCK_AD { get; set; }

        public Nullable<int> ID_PRODUCT { get; set; }


        [DisplayName("Ville")]
        [Required(ErrorMessage = "La ville est obligatoire")]
        public string CITY_AD { get; set; }

        [DisplayName("Pays")]
        [Required(ErrorMessage = "Le pays est obligatoire")]
        public string COUNTRY_AD { get; set; }

        //[ForeignKey(nameof(ID_PRODUCT))]
        public virtual T_PRODUCT T_PRODUCT { get; set; }
    }
}
