//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio_Tourist.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class T_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PRODUCT()
        {
            this.T_AD = new HashSet<T_AD>();
        }
    
        public int ID_PRODUCT { get; set; }
        [DisplayName("Catégorie")]
        [Required(ErrorMessage = "La catégorie est obligatoire")]
        public string CATEGORIE_PRODUCT { get; set; }

        [DisplayName("Quantité")]
        [Required(ErrorMessage = "La quantité est obligatoire")]
        public int QUANTITE_PRODUCT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AD> T_AD { get; set; }
    }
}
