//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bio_Tourist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_USER()
        {
            this.T_AD = new HashSet<T_AD>();
        }
    
        public int ID_USER { get; set; }
        public string LAST_NAME_USER { get; set; }
        public string FIRST_NAME_USER { get; set; }
        public int AGE_USERS { get; set; }
        public int NUM_STREET { get; set; }
        public string NAME_STREET { get; set; }
        public int POSTAL_CODE { get; set; }
        public string CITY_USER { get; set; }
        public string COUNTRY_USER { get; set; }
        public string EMAIL_USER { get; set; }
        public int NUM_USER { get; set; }
        public string PASSWORD_USER { get; set; }
        public string CIVILITY_USER { get; set; }
        public int ID_ROLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_AD> T_AD { get; set; }
        public virtual T_ROLE T_ROLE { get; set; }
    }
}
